### ISSUE TITLE
Code for abbreviation extraction?

### ISSUE THREAD

**Issue by danyaljj** [davidsbatista/lexicons#1]
Do you have the code for extracting the abbreviations? 
https://github.com/davidsbatista/lexicons/blob/master/wikipedia-acronyms.txt

**Comment by davidsbatista** [comment]
"A Simple Algorithm for Identifying Abbreviation Definitions in Biomedical Text"
http://biotext.berkeley.edu/papers/psb03.pdf

Java implementation: http://biotext.berkeley.edu/code/abbrev

**Comment by danyaljj** [comment]
Thanks!
